version: '3.3'
services:
  db:
    build: .
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3314:3306"
    volumes:
      - .initdb.d:/docker-entrypoint-initdb.d
      - .conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
